name: Gradle CI

on:
  push:
    branches:
      - 'version/*'

permissions:
  contents: read

jobs:
  build:
    environment: Kilt Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    # Taken from https://github.com/CaffeineMC/sodium-fabric/blob/1.19.3/dev/.github/workflows/gradle.yml
    - name: Cache/Uncache
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/loom-cache
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Setup Dev Environment
      run: ./gradlew setupDevEnvironment
    - name: Build artifacts
      run: ./gradlew remapJar
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Kilt Build JARs
        path: build/libs/Kilt-*.jar
